### PR TITLE
Feature/analysis list spoiler

### PR DESCRIPTION
**Pull request by ahaurw01**
To come after #77. 

Shows card images next to the deck list when you hover over a row. The images do not show on mobile yet. I'll probably make another PR to try out solutions on that front.

### CODE REVIEW

**Comment by ahaurw01** [comment]
I might try out doing the expansion thing you mentioned yesterday a la google inbox. If that works well maybe we can ignore this PR.

**Comment by ahaurw01** [comment]
Or possibly you were only thinking of that interaction style for the card search listing?

**Comment by SirZach** [comment]
was thinking that interaction style would replace the deck card listing page only as it's nice to have the single resource route for the individual card making the url /cards/:card_id play nicely

**Comment by ahaurw01** [comment]
Sounds great to me.

**Comment by SirZach** [comment]
are you thinking about tackling the expand the card for the x-paper-items in this branch? i think that functionality could be nice on the decks list page. i wouldn't mind taking a crack at that if you'd like to pass the buck

**Comment by ahaurw01** [comment]
All you if you're in the mood. I'd opt for putting that in a separate pr anyhow.

**Comment by SirZach** [comment]
do you want to merge this in? i wasn't sure if you were holding off or not

**Comment by ahaurw01** [comment]
Whoops sorry, forgot to merge this guy.

**Comment by SirZach** [comment]
this is beautiful btw. we need to show the cards on the left side for the deck builder page but it's awesome!

**Comment by ahaurw01** [comment]
Thanks :smiley: Good call.

**Pull request merged**
