### PR TITLE
Bugfix/magnify z index

### PR DESCRIPTION
**Pull request by ahaurw01**
Well, I've now spent entirely too much time on a fool's errand of trying to create a single magnifier component that gets updated whenever a certain card is magnified. I ran into some difficulties with that approach and reverted to the hack I should have started with in the first place.

### CODE REVIEW

**Comment by ahaurw01** [comment]
Addresses one item of https://github.com/SirZach/bbbbbbbbbbbbbbb/issues/197.

**Comment by SirZach** [comment]
sorry about the delay and overall lack of activity. will try to get some PRs out myself soon. thanks for this!

**Comment by ahaurw01** [comment]
No worries. We're headed to a campsite in NY right now, so probably minimal
contact from me for the weekend. I'll try to avoid the bears!

**Comment by SirZach** [comment]
I'm in NJ this weekend and in the Poconos the week after. Gotta start finding time somewhere else!

**Comment by ahaurw01** [comment]
Oh nice! Have fun

**Pull request merged**
