### PR TITLE
Tapped Out import, display import errors

### PR DESCRIPTION
**Pull request by ahaurw01**
Accepts imports in the style of tappedout.net's exports. Also now displays an import error section on the deck builder page so you know what you messed up.

Needs a few tests which I will get around to creating one of these days...

### CODE REVIEW

**Comment by SirZach** [comment]
Do you think the UI should indicate the format of the deck you're importing?

**Comment by ahaurw01** [comment]
Possibly. What do you think that could look like?

**Comment by SirZach** [comment]
I don't think this is necessary to get your PR in BTW but maybe something like a ? icon with a hover-over that shows the different formats of the strings you can enter. Or maybe some fancy sauce like putting green checkmarks next to each valid line and red x's next to improperly formatted lines.

I think a lot of fun and unnecessary time could we be wasted here :)

**Comment by ahaurw01** [comment]
I love these ideas : )

**Pull request merged**
