### PR TITLE
Gameplay/library search

### PR DESCRIPTION
**Pull request by SirZach**
i realize not all the transitions are completely there. i figure it's something we can do as part of a CSS cleanup effort at the end

### CODE REVIEW

**Comment by SirZach** [comment]
to address #134

**Comment by SirZach** [comment]
tests are failing on the CL but working in the browser. still investigating why

**Comment by ahaurw01** [comment]
Cool. I'll help check it out tonight as well. Looking forward to this one :)

**Comment by ahaurw01** [comment]
This is awesome - great work!

**Comment by ahaurw01** [comment]
One note - I see the context menu on my small screen is now off the page. 

screen shot 2015-06-08 at 9 05 13 pm

It seems even google inbox doesn't have a great approach for context menus. They're kind of all over the place and don't always fit on the screen. We can revisit later if need be.

**Comment by ahaurw01** [comment]
I see the same thing you did with the card container going off the bottom of the screen a little. Looks like it's due to `height: 100%` while being `position: fixed`. Possibly `height: calc(100% - Xpx)` or setting `top` and `bottom` would do the trick.

**Comment by ahaurw01** [comment]
I think this panel works really well. Good stuff :smile_cat:

**Comment by SirZach** [comment]
you and your unlimited emoticons. i'll create an issue to address CSS overhaul at the end before a 1.0 release

**Comment by ahaurw01** [comment]
:+1:

**Pull request merged**
