### PR TITLE
Enhancement/deck builder

### PR DESCRIPTION
**Pull request by SirZach**

### CODE REVIEW

**Comment by SirZach** [comment]
addresses #33

**Comment by SirZach** [comment]
ok, there's still some opportunities to clean up some other things as we go but for the most part, it's in a better place

**Comment by ahaurw01** [comment]
Love these changes. A couple things I noticed:
 
- The card image on the search result expansion can get really huge and pixelated if the screen is wide. Might need some max width there.
- It's not quite clear at first which plus button does what on the search result hover. 
- `:hover` styles might need to also be applied to `:focus` for touch devices to take advantage.
- It'd be nice if the hover state doesn't alter the size of the element you're hovering. E.g. the deck table rows can get kinda big if the screen width is small. A little jarring, but definitely not the end of the world. To fix we might have to do something like make the buttons `position: absolute` but pay attention to the space that may or may not be available if the row width is not that forgiving. Here's an example of what trello does. Could be tricky.

screen shot 2015-05-03 at 9 24 23 pm

I like how clicking the deck table searches for that card on the left side.

I'm fine merging this and then we can continue to iterate on the thoughts above - up to you.

**Comment by SirZach** [comment]
I really appreciate the feedback!

What do you think about not showing the card when you click to expand? We could show the card image on hover of the card, similar to hit you implemented the deck table. 

Do you have a thought on how to make it more clear what the plus buttons do? I was hoping to rely on user experimentation. 

Im not familiar with how focus styles work on touch devices. I'll play with it. 

Uggh to your last bullet point. I was trying to fix it but got impatient. I'll give it another go. 

Overall you like the changes though?

**Comment by SirZach** [comment]
BTW, what width are you assuming when testing the mobile experience?

**Comment by ahaurw01** [comment]
Nice, I like these changes. I'm good with not showing the card when expanding the search result, possibly even on hover. The card info is all there and it looks nice and straightforward.

The text buttons look good. This is more of a nit, and I really don't know what I'm talking about here, but I remember the material design docs saying to use raised buttons sparingly, like for a main callout on a page, and instead using flat buttons on tiles and cards. But I'm good either way here.

We can defer the issue of the deck table rows expanding - not super concerned.

When testing out mobile I've just been using the chrome mobile emulator button next to the magnifying glass and choosing a device like iPhone 5 or something. That also seems to emulate the touch events nicely to test out the `:focus` styles.

I like it! I say ship it if you're ready.

**Comment by SirZach** [comment]
BTW, I'll never believe you when I say "I really don't know what I'm talking about."

**Pull request merged**
