### PR TITLE
Gameplay/library context

### PR DESCRIPTION
**Pull request by SirZach**
addresses #115

### CODE REVIEW

**Comment by ahaurw01** [comment]
I am pumped to pull this down

**Comment by SirZach** [comment]
I hope you enjoy! I'm thinking there may be a few style changes like border
radius and stuff but I'm hoping we can come back and do a clean sweep after
its more complete

**Comment by ahaurw01** [comment]
Sounds like a great plan. :+1:

**Comment by ahaurw01** [comment]
Looks awesome. A couple thoughts, though we can defer these and merge. I'll let you hit the button when ready.

* I'm thinking it'd be nice to close the context menu after clicking an option, and ideally on clicking anywhere else on the screen (like bootstrap's menu behavior).
* The model saving can take quite some time, especially on actions that touch every card in your deck, like shuffling. I watched the web socket frames while clicking "shuffle" and there's a crazy amount of action going on there. It bogs down the UI thread, which I wouldn't have expected. I had shuffles that locked the UI thread for ~5 seconds. Not sure at all why it's that dramatic. I'm wondering if we'll have to move to modeling the game in some serialized fashion so it's one update on each change instead of 60+.

**Comment by SirZach** [comment]
ok responses
1) I disagree with closing when click an option. I thought that's what I expected at first but I'm imagining you mulligan and now you need to draw 6 instead of 7. It makes sense if you could just click "Draw Card" again and again. Or maybe the way you mulligan is by "Draw 7", see what's in your hand, "Return All Cards" and then "Draw Hand" again. I'm just not sure it should be closing every single time in between those interactions. I want bootstrap's behavior of closing when clicking outside of it but honestly I'm clueless on how to do it. I could register every context-menu component on app controller and then have the app's view click handler close all the registered context-menus but that doesn't do us any good if you click on a view that doesn't keep on sending up the click action.

2) I was noticing performance problems with the model saving. I am okay with deferring it and spending time later looking at the CPU profiler to determine what is actually causing the problem.

**Comment by ahaurw01** [comment]
I'm totally cool deferring these thoughts. The core functionality is great - let's roll with it!

**Pull request merged**
