### PR TITLE
Feature/public deck list

### PR DESCRIPTION
**Pull request by ahaurw01**
A basic start to issue https://github.com/SirZach/bbbbbbbbbbbbbbb/issues/99.

Shows an infinite scroll list of all decks, sorted by created date descending. This replaces your personal deck list at the moment, so I'll move to either filter by "mine only" or show them on some sort of profile page soon. What do you think?

### CODE REVIEW

**Comment by SirZach** [comment]
i like this a lot. i can definitely see room for expansion, perhaps adding toggleable filters like on the deck edit page? do you think we should add the filters for showing "mine only" before beta or for 1.0? i'm down with either

**Comment by ahaurw01** [comment]
Oh yeah, totally agree with the toggled filters a la deck building. Maybe that can grow over time. Stuff I had in mind for that - creator, deck name, legality, colors, contains certain card? Lots of options there. I can't tell if it's best to include the "mine" filter as one of these toggled guys or as something else, even as drastic as another link on the side nav. Any opinions there? I'll go ahead and merge this PR and I'll create a ticket for toggled filters.

**Comment by SirZach** [comment]
I think we need the ability to toggle to your own decks before beta. I
think it's a must.

**Comment by ahaurw01** [comment]
Yep, I agree.

**Pull request merged**
