### PR TITLE
can close context-menu when you click outside of the menu

### PR DESCRIPTION
**Pull request by SirZach**
this should allow us to have multiple context-menus on the page and they'll close when you click outside of the menu

### CODE REVIEW

**Comment by SirZach** [comment]
oh, it means each context-menu will need to have an id associated with it but that should not be a problem

**Comment by SirZach** [comment]
these tests pass locally in the browser

**Comment by ahaurw01** [comment]
Hell yes. Nice work. I pushed a small change to allow us to not have to explicitly set the id. I was reminded by the docs this morning that the public facing api for getting the id is via `.get('elementId')` and Ember apparently sets a default id on everything equivalent to `Ember.guidFor(<the component>)` - that thing that looks like `"ember1234"`. Also a small change for phantom not implementing `.bind` which was failing that test.

**Comment by ahaurw01** [comment]
See what you think about the changes - merge when ready!

**Comment by SirZach** [comment]
Clever fixes, thanks!!

**Comment by ahaurw01** [comment]
Sure thing - you did the hard part. :smile: 
I had seen the jQuery event namespace thing used before but didn't really understand what it was doing until reading the docs just now. Good usage of that.

**Comment by SirZach** [comment]
Oddly enough using the namespace was the only way I could remove the
binding. All other variances of the on api wouldn't honor the off :(

**Pull request merged**
