### PR TITLE
moving out the loading cards from the application route. had to remove t...

### PR DESCRIPTION
**Pull request by SirZach**
...he Ember.run.next in session since doing a get('session.isAuthenticated') would return 'undefined' without something in the beforeModel hook of the application route causing enough of a delay for that to come back. very unexpected

addresses #30

### CODE REVIEW

**Comment by SirZach** [comment]
very curious on your feedback about removing the Ember.run.next. Seems even removing that there's still a possible race condition.

**Comment by ahaurw01** [comment]
I hadn't until now stopped to look at what firebase is doing with that `onAuth` callback. It seems they are always calling our callback synchronously with the same value as what you get when you do `this.get('ref').getAuth()`. Or of course if you aren't logged in then it won't be called yet. So I suppose it makes sense that putting the business logic inside of an `Ember.run.next` (putting that stuff on a fresh call stack once the thread is free again) would cause the initial route's `beforeModel` to not have access to the auth object yet.  
It does seem like a good idea to put all our callbacks in `session.js` in `Ember.run`s. Doing this locally within the `onAuth` callback doesn't result in any race conditions for me. At least not yet. :smile: 
I see all of the other callbacks I wrote are not wrapped in `Ember.run` - my bad.

**Comment by ahaurw01** [comment]
I'd vote for merging this as-is if you like. We can always introduce the `Ember.run`s in another PR.

**Comment by SirZach** [comment]
If you pull this branch down, uncomment the run loop and refresh on the
decks list page, you don't get booted to the games page because
session.isAuthenticated is undefined?

**Comment by ahaurw01** [comment]
Yep, I see that behavior. When I change `Ember.run.next` to `Ember.run`, it behaves as expected.

**Comment by SirZach** [comment]
Let's merge this and come back later and clean it all up

**Comment by ahaurw01** [comment]
Sounds great.

**Pull request merged**
