### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Createor**
Adding workaround for http://discuss.emberjs.com/t/ember-app-wont-load-resource-integrity-error-in-chrome/8733

### CODE REVIEW

**Comment by SirZach** [comment]
Nice thanks man!

**Comment by ahaurw01** [comment]
:+1:!!

**Comment by SirZach** [comment]
So webatrice.com looks like shit right now on Chrome 45. This patch should've fixed it but Heroku is not deploying for some reason. Looking into to it now...

**Comment by SirZach** [comment]
Ok the build went through and the integrity tag is there but it's still shitting the bed on Chrome 45 :(

**Comment by Createor** [comment]
Looks like maybe this is specifically an issue with chrome? https://code.google.com/p/chromium/issues/detail?id=527286

**Pull request merged**
