### PR TITLE
Choose deck in game

### PR DESCRIPTION
**Pull request by ahaurw01**
To come after https://github.com/SirZach/bbbbbbbbbbbbbbb/pull/6

Shows decks of yours that are eligible for play when you jump into a game. Clicking on a deck tile selects the deck for your `GameParticipant` model and saves the game state. I'll leave the state management and forward progress for your tickets to show ready checkboxes and set active game state.

Any ideas for what we want to show around the deck tiles? Anything like "Choose a deck" maybe?

### CODE REVIEW

**Comment by ahaurw01** [comment]
Until #6 is merged, here's a view of the differences: https://github.com/SirZach/bbbbbbbbbbbbbbb/compare/feature/introduce-games...SirZach:feature/choose-deck-in-game

**Comment by SirZach** [comment]
this guy should be good to go now, right?

**Comment by ahaurw01** [comment]
Yeah, I might have to merge master into it for it to figure out what is actually new. There's a lot here, but likely we'll adjust the approach as we go forward. We can merge now, or comments/input are absolutely welcome if you see some concerns.

**Comment by SirZach** [comment]
I'd say we just merge it all in and we can start from after the merge. It sounds like I may need to delete my one deck from firebase, right?

**Comment by ahaurw01** [comment]
Sounds good to me. That's probably best, or you could manually create the relationship on your user model. Or export it locally before merging in master, then import it back :smile:

**Pull request merged**
