### PR TITLE
updated the deck landing page to be better

### PR DESCRIPTION
**Pull request by SirZach**

### CODE REVIEW

**Comment by SirZach** [comment]
started moving some files over to pods. i think it really helps figure out what you're looking at, especially when you're not developing in the project frequently

**Comment by SirZach** [comment]
you can get a preview of the decks at http://dev-webatrice-pr-236.herokuapp.com/decks/list i'll tackle removing the infinity model out next

**Comment by ahaurw01** [comment]
Looks awesome! I noticed that it renders slightly differently in Firefox:

image

It seems like Chrome knows how to break long words by hyphen, but Firefox doesn't. ("zach.mcgonigal-email") If I apply `max-width: 174px` instead of `flex-basis` on those guys, it seems to make them all the same width. Or possibly we want `word-break: break-all` on the user link in addition or instead. 

Either way, feel free to merge this when you like! I love how it looks. What are you thinking for pulling out infinity model?

**Comment by SirZach** [comment]
`max-width` makes more sense than `flex-basis` now that we can't allow the tiles to get any wider due to the image constraints so that's a welcome change. if you wouldn't mind committing that that'd be great. 

For pulling out infinity model, I was just thinking of fetching all the decks normally. I think we were having perf issues when fetching all the decks meant fetching all the cards but I'm not sure we have that problem anymore. I'm sure we'll have to do perf tuning again in the future. If it feels like undoing too much work then I might enlist your help to see what's broke there...

**Comment by ahaurw01** [comment]
Cool, that sounds good. I agree that we probably won't see the hiccup we used to when it would turn around and fetch a million cards to just show the decks.

**Comment by SirZach** [comment]
What do you think of the pods?

**Comment by ahaurw01** [comment]
Cool with the pods. I don't have a big preference one way or the other. We use them at work and it seems to work pretty well for us.

**Comment by ahaurw01** [comment]
Updated the styling. If you're cool with it, feel free to merge!

**Comment by SirZach** [comment]
Thank you!

**Pull request merged**
