### PR TITLE
Ember.run all the things!

### PR DESCRIPTION
**Pull request by ahaurw01**
Sprinkles `Ember.run` into the session initializer.

### CODE REVIEW

**Comment by SirZach** [comment]
So I may have not fully understood before why everything needs to be in run loops...

**Comment by ahaurw01** [comment]
Yeah, my understanding comes and goes. Not sure I ever fully got the deal. Something about foreign libraries executing code that touches ember objects and things possibly getting out of sync. Although I thought a `.set` should kick off an auto run loop. Who knows.

**Comment by SirZach** [comment]
let us merge and hope to never speak of it again

**Comment by ahaurw01** [comment]
:hear_no_evil: :see_no_evil: :speak_no_evil:

**Pull request merged**
