### PR TITLE
adjust card fetching so it can be done right when the game starts ins…

### PR DESCRIPTION
**Pull request by ahaurw01**
…tead of on refresh

### CODE REVIEW

**Comment by SirZach** [comment]
My experience of computed properties returning promises has not been great. Do you think we could move that logic to the action handler for when you click Ready?

**Comment by ahaurw01** [comment]
I thought about that, might be doable. It'll have to be an observer on the player ready states since it needs to know about both player 1 and 2. I'll give it a shot.

**Comment by SirZach** [comment]
if you had success with it being a computed property we can keep it until a different opportunity prevents itself. no need to stop from moving forward.

**Comment by SirZach** [comment]
one bad thing i noticed here is that the computed properties based on <code>cards.@each.cardId</code> recompute for every single card coming back on an individual basis instead of just when all the cards resolve at once.

```
[undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", undefined, "Belligerent Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", undefined, "Belligerent Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", undefined, "Megantic Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", undefined, "Megantic Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", undefined, "Striking Sliver", undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", undefined, "Striking Sliver", undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", undefined, undefined, undefined, undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", undefined, undefined, "Plains", undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", undefined, undefined, "Plains", undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", "Sentinel Sliver", undefined, "Plains", undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", "Sentinel Sliver", undefined, "Plains", undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", "Sentinel Sliver", "Constricting Sliver", "Plains", undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", "Sentinel Sliver", "Constricting Sliver", "Plains", undefined, undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", "Sentinel Sliver", "Constricting Sliver", "Plains", "Hive Stirrings", undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", "Sentinel Sliver", "Constricting Sliver", "Plains", "Hive Stirrings", undefined, undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", "Sentinel Sliver", "Constricting Sliver", "Plains", "Hive Stirrings", "Sliver Hive", undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", "Sentinel Sliver", "Constricting Sliver", "Plains", "Hive Stirrings", "Sliver Hive", undefined]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", "Sentinel Sliver", "Constricting Sliver", "Plains", "Hive Stirrings", "Sliver Hive", "Venom Sliver"]
battle-field.js:20 ["Manaweft Sliver", "Forest", "Sliver Hivelord", "Mountain", "Druid's Deliverance", "Thorncaster Sliver", "Transguild Promenade", "Blur Sliver", "Predatory Sliver", "Belligerent Sliver", "Door of Destinies", "Syphon Sliver", "Mutavault", "Megantic Sliver", "Bonescythe Sliver", "Galerider Sliver", "Striking Sliver", "Sentinel Sliver", "Constricting Sliver", "Plains", "Hive Stirrings", "Sliver Hive", "Venom Sliver"]
```

**Comment by SirZach** [comment]
also as another side effect, the game page transitions all the way in now without the card images - showing the red cards turn into real cards as the xhr requests are fulfilled. i think an observer might be worth the engineering shame to avoid these problems

**Pull request merged**
