### PR TITLE
Jscs

### PR DESCRIPTION
**Pull request by SirZach**
addresses #225 

If you notice, I started out substituting Ember.Component and Ember.computed for destructed const variables but that effort was getting too huge. I plan on updating files to that syntax as I go along and edit them for new features or whatever. I also want to utilize Ember.gets and Ember.sets instead of doing <code>variable.get()</code> simply because I've gotten burned a couple of times on trying to do a get on an undefined variable.

### CODE REVIEW

**Comment by ahaurw01** [comment]
Thanks man, this branch is looking fresh as hell. I'll never bow to the no-space-between-function-and-open-paren fascists, though. Just kidding :smile: 
I say merge at will! Anything else you wanted to tweak before?

**Comment by SirZach** [comment]
I hear you on the spaces and thought about ignoring that rule. If you'd prefer to ignore it I can do that

**Comment by ahaurw01** [comment]
Not a problem. I know that's the style they follow and I'm totally cool with it.

**Comment by SirZach** [comment]
excellent! maybe i'll finally start working on one of those 1.0 features...

**Comment by ahaurw01** [comment]
:smile:

**Pull request merged**
